misc:
  datadir: data/
  model_path: models/lgbm-grid.pkl
  prediction_path: submissions/lgbm-grid.csv
  random_state: 1126
grid_args:
  n_jobs: 16
  cv: 10
model:
  name: LGBMClassifier
  args:
    n_estimators: 1024
    random_state: 1126
    n_jobs: 2
    class_weight: balanced
  param_grid:
    max_depth: [2, 3]
    learning_rate: [0.2, 0.1, 0.05]
    reg_alpha: [0.0, 0.00001, 0.001]
    reg_lambda: [0.0, 0.00001, 0.001]
