misc:
  datadir: data/
  cv_model_path: models/lgbm-grid-cv.pkl
  best_model_path: models/lgbm-grid-best.pkl
  prediction_path: submissions/lgbm-grid.csv
  random_state: 1126
grid_args:
  n_jobs: 16
  cv: 8
model:
  name: LGBMClassifier
  args:
    n_estimators: 128
    random_state: 1126
    n_jobs: 2
    class_weight: balanced
  param_grid:
    boosting: [gbdt, dart]
    max_depth: [2, 3]
    learning_rate: [0.4, 0.2, 0.1, 0.05]
