misc:
  datadir: data/
  cv_model_path: models/xgboost-grid-cv.pkl
  best_model_path: models/xgboost-grid-best.pkl
  prediction_path: submissions/xgboost-grid.csv
  random_state: 1126
grid_args:
  n_jobs: 16
  cv: 8
model:
  name: XGBClassifier
  args:
    n_estimators: 128
    random_state: 1126
    n_jobs: 2
  param_grid:
    booster: [gbtree, dart]
    max_depth: [2, 3]
    scale_pos_weight: [1.25, 2, 3.75]
    learning_rate: [0.4, 0.2, 0.1, 0.05]
