misc:
  datadir: data/
  model_path: models/xgboost-base.pkl
  prediction_path: submissions/xgboost-base.csv
  random_state: 1126
grid_args:
  refit: True
  n_jobs: 16
model:
  name: XGBClassifier
  args:
    n_estimators: 1024
    max_depth: 3
    scale_pos_weight: 2.0
    random_state: 1126
    n_jobs: 4
  param_grid:
    null
