global_settings:
  refit: True
  n_jobs: 16
  random_state: 1126
model:
  name: XGBClassifier
  args:
    n_estimators: 1024
    random_state: 1126
    n_jobs: 2
  param_grid:
    max_depth: [2, 3, 4]
    scale_pos_weight: [1.25, 2, 3.75]
